### ISSUE TITLE
Items dont work. 

### ISSUE THREAD

**Issue by BloodDragon2580** [Skamer/Syling-Tracker#1]
By me the Quest items at the Tracker dont work. Must search everytime in my bag for the Quest items.

**Comment by Skamer** [comment]
Hello,

This is intended that nothing is happening when clicking the item quest from Tracker. For explaining the reason:

The addon displays the quest item as simple texture. If i would that clicking it will use the item, i need to use an ActionButton. The problem being this is a Secure Frame.

**The Secure Frames**

The Secure Frames are frames subjected to strict restrictions by Blizzard. For example, some functions are prevented to be called when the player in in combat. Among them, there is one controlling the frame position. If i call it when the player is in combat, the following error will occur:  the addon "XXX" attempts to call a protected a function. I think you have probably ever seen it once. That means in our case, the quest item cannot be moved in combat.

You may be tempted to say : this concerns only the quest items. But in reality this isn't the case because there is exists an another behavior related to Secure Frames, the one propagating their restrictions to other frames which are anchored to them and to their parents. If we com back in the addon case, this would say the item quest, by cascade effect, will make the tracker and all its elements inside unable to be moved when the player is in combat. Obviously, this will break completely the addon.

If Blizzard are able to do that in their UI, it's because their addons are considered as secure, so there are no restriction for them.

**Is there a workaround ?**

The workaround i have planned is to provide an action bar containing all the quest items. This action bar will indirectly be secure, but here it's not in problem because it won't be anchored to Tracker. You will also be able to move the action bar where you want. The Quest item in the tracker is simply there for saying this quest has an item, and the action bar will handle providing a quick access to quest items.
