### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by Arkewas** [Skamer/Syling-Tracker#105]
Hello,
I'm using Syling Tracker 2.4.5 and I get this error:

6x [ADDON_ACTION_BLOCKED] AddOn 'SylingTracker' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerContainer.lua"]:101: in function <...ectiveTracker/Blizzard_ObjectiveTrackerContainer.lua:43>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXML/MixinUtil.lua"]:341: in function <Blizzard_SharedXML/MixinUtil.lua:340>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {

I'm using Syling Tracker in conjunction with TomTom addon, if this can help. BTW the interaction between Syling Tracker and TomTom works very well

**Comment by Skamer** [comment]
Hello, 

This error is due to taint issues. This type of error is often a nightmare to track down because it can be caused by other addons. 

In the War Within, Blizzard changed quite a few things in their tracker, and now it forces their tracker to be re-displayed for every events. I modified my method, and i believe this error may coming from this new one. I have another alternative, but it has a small downside as well.

**Comment by Arkewas** [comment]
I understand, thanks for the clarification.
