### ISSUE TITLE
Quests objective text not always fully visible.

### ISSUE THREAD

**Issue by Arkewas** [Skamer/Syling-Tracker#108]
Hello Skamer,

as you can see from the attached screenshot the quest "Salvate le savane" has its text truncated on the first line while the quest "Ak'Zeloth" has its text correctly visible on two lines. Syling Tracker version 2.5.0
![Syling Tracker quest text](https://github.com/user-attachments/assets/e1edc87b-bc73-4620-a81e-ba0fc0a44c42)

**Comment by Skamer** [comment]
Hello,

To be honest, it's a bug that i've encountered very very rarely. That's why it's quite difficult for me to provide an immediate fix. A friend who uses my addon had a similar problem, and he told me it was probably caused by the font. 

Do you encounter this problem all the time ? I'd like to know the frequency.

**Comment by Arkewas** [comment]
Hello,
it occurs rarely and I don't get lua errors so I understand it's not easy to fix it. Anyway it's a minor issue so I can stand with it.
