### ISSUE TITLE
Blizzard objective tracker appears constantly

### ISSUE THREAD

**Issue by RyadaProductions** [Skamer/Syling-Tracker#29]
**Describe the bug**

**Do you have an error log of what happened?**
No error is generated

**To Reproduce**
1. Join a dungeon
2. Blizzard objective tracker appears

**Expected behavior**
Blizzard objective tracker should remain hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/24586388/100252194-e8327c80-2f3f-11eb-8fc8-e5dce85a2ffb.png)

**What is the version of SylingTracker you use ?**
0.5.1

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v264
- Scorpio: v057

**Additional context**
Other actions cause the same behavior. Once I figure those out I will list them as well.

**Comment by Skamer** [comment]
All works fines from my side. I think your issue may be caused by an another addon.  

When Syling Tracker hiding the Blizzard objective tracker, this also unregister the "OnEvent" script to avoid the handler related to it showing the tracker for every progress update.
https://github.com/Skamer/Syling-Tracker/blob/6c6cdd6c24d217d3a2c13a0957570e4da7fe6760/SylingTracker.lua#L78
If an another addon for some reason put the original handler to this "OnEvent" then the Blizzard objective tracker will appear to each progress update.

**Comment by RyadaProductions** [comment]
Found the addon that was causing this, Benik ui V3.
It hides the UI while using a flight path and then unhides it again. 
But it does not have proper support for Syling tracker because Syling doesn't get hidden by it and the moment you arive at your destination it unhides the default Objective tracker
