### ISSUE TITLE
Good tracker but unfortunately with few Updates

### ISSUE THREAD

**Issue by RAtwood90** [Skamer/Syling-Tracker#68]
Hello Skamer!

I really love your Tracker but it's missing so much editable Options like:

Font, Font Color, Font Size for all the Texts and Headers.

Statusbar Texture, Color change.

Checkbox Texture, Color change also disabling Function. (For some who only wants to see then the Quest is completed by turning the Text Green and Checkmarked.

Size Option for the Windows Width and Height.

Also Option to customize the Tooltip then right click.

The Options you actually got are barely rare sadly at the Moment. 

And for me as UI Creator i can't get the Style to Match with my UI.

May Updates will be come in the Future maybe not.

Stay Healthy! 

Good Bye my Friend.

**Comment by Skamer** [comment]
Thanks for your feedback.

I want to reassure you the addon will get updates.

**Comment by RAtwood90** [comment]
> Thanks for your feedback.
> 
> I want to reassure you the addon will get updates.

Well good to know.

The Functions seems to be working quite good.

But all the Default Customization Options sadly missing.

Hopefully they will add soon as u have Time Mate!

**Comment by Skamer** [comment]
For giving more information.

I'm developing a feature allowing take as account the user settings directly from the skin definitions. It's still experimental, and i need to fix issue before to expand that on the addon elements. 

Something is worth to say, i plan to add a way to creating its own skins but it targets more the advanced users as this need to know the lua tables. 

For example, here is the default skin for the objectives.
https://github.com/Skamer/Syling-Tracker/blob/ff845c284039eb163fa38df1369f94fab37f6715/UI/ObjectiveView.lua#L630-L751

**Comment by RAtwood90** [comment]
> For giving more information.
> 
> I'm developing a feature allowing take as account the user settings directly from the skin definitions. It's still experimental, and i need to fix issue before to expand that on the addon elements.
> 
> Something is worth to say, i plan to add a way to creating its own skins but it targets more the advanced users as this need to know the lua tables.
> 
> For example, here is the default skin for the objectives.
> 
> https://github.com/Skamer/Syling-Tracker/blob/ff845c284039eb163fa38df1369f94fab37f6715/UI/ObjectiveView.lua#L630-L751
> 
> From this way you could override the default skin in creating a skin definition with for value:
> 
> ```lua
>  [ObjectiveView] = {
>     StatesStyles = {
>       [ObjectiveView.State.Progress] = {
>         Text =  Color.WHITE
>       }
>     }
>   }
> ```
> 
> In the above example, the objective text will now be colored in white (instead of grey) when it's in progress.

Sounds good! But there will be also the Default Customization for Noob Users right? 

Or will this Addon go the Way like Weakaura?

**Comment by Skamer** [comment]
For changing an ui property, there are two ways:
- Method 1 (noob users): you can do that from a GUI interface (color picker, checkbox, button, dropdown, ...)
- Method 2 (advanced users): you can do that in creating a skin definition with LUA tables.

If the Method 1 is available, 99,99% would use it even myself, this is more simple. But in the case where this one is not here because either it's not yet implemented or either too complex to be here. In these case there, you can use the second method as fallback. 

It's important to note you can combine the both method, changing a ui property with the method 1 not prevent you to use the method 2 for an another property. 

> But there will be also the Default Customization for Noob Users right?

The addon uses this skin system internally from the beginning, so the default appearance won't change with you have already now.
