### ISSUE TITLE
Ability to adjust length and width of quest window

### ISSUE THREAD

**Issue by KuriFoxy** [Skamer/Syling-Tracker#99]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to make the quest log longer downwards

**Describe alternatives you've considered**
Unsure
 
**Additional context**
I use a big monitor and would be awesome if there was a bit more control over the length of the quest log so theres not an awkward space inbetween, the addons amazing but thats my only gripe
![Wow_62HrJ58imr](https://github.com/user-attachments/assets/f8a9a2f4-fb75-4f16-85ee-a00def9be577)

**Comment by Skamer** [comment]
When the tracker is unlocked, there is a small resizer located to the bottom right. This is true can be hidden because it's inner and the others elements can be top of it. I'll bring improvements on this side, and also allow the size to be changed from in the options.

![image](https://github.com/user-attachments/assets/121c052a-bc85-47d8-ad0a-050c296aeb32)

**Comment by KuriFoxy** [comment]
Oh didnt know that. thanks :)
